version: '3.3'
services:
  db:
    image: postgres:14
    container_name: psql-connection
    volumes: 
    
      - ./data/db:/var/lib/postgresql/data 
    # hostname: db
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=user3
      - POSTGRES_PASSWORD=123

  web:
    restart: always
    image: prj-image
    container_name: prj-container-ecommerce
    build: 
      context: ./project_ecommerce
      dockerfile: Dockerfile
    volumes:
      - ./project_ecommerce:/code
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_NAME=ecommerce
      - POSTGRES_USER=user3
      - POSTGRES_PASSWORD=123
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db     
  adminer:
    image: adminer
    restart: always
    container_name: project-adminer
    depends_on:
      - db
    ports:
      - 8090:8090

